apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db-server
  template:
    metadata:
      labels:
        app: mongo-db-server
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "buse"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "123456"
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db 
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc